name: CI for Django

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install and Build frontend dependencies
      run: |
        cd client
        npm install
        npm run build

    - name: Check if server starts
      run: |
        python manage.py runserver 8000 &
        sleep 10
        curl -f http://127.0.0.1:8000 || exit 1
